export const positions = [
  { title: "GK → Goalkeeper", value: "GK", zone: "goalkeeper" },
  { title: "CB → Centre-back", value: "CB", zone: "defence" },
  { title: "LB → Left-back", value: "LB", zone: "defence" },
  { title: "RB → Right-back", value: "RB", zone: "defence" },
  { title: "DMF → Defensive Midfielder", value: "DMF", zone: "midfield" },
  { title: "CMF → Central Midfielder", value: "CMF", zone: "midfield" },
  { title: "LMF → Left Midfielder", value: "LMF", zone: "midfield" },
  { title: "RMF → Right Midfielder", value: "RMF", zone: "midfield" },
  { title: "AMF → Attacking Midfielder", value: "AMF", zone: "midfield" },
  { title: "LWF → Left Wing Forward", value: "LWF", zone: "attack" },
  { title: "RWF → Right Wing Forward", value: "RWF", zone: "attack" },
  { title: "SS → Second Striker", value: "SS", zone: "attack" },
  { title: "CF → Centre Forward", value: "CF", zone: "attack" },
] as const;

export type Position = (typeof positions)[number]["value"];
export type Zone = (typeof positions)[number]["zone"];

export const strengthCategories = [
  "physical",
  "defending",
  "passing",
  "dribbling",
  "shooting",
  "goalkeeping",
  "mental",
] as const;

export type StrengthCategory = (typeof strengthCategories)[number];

export const strengths = [
  { title: "Explosive pace", value: "explosive-pace", category: "physical" },
  { title: "Quick acceleration", value: "quick-acceleration", category: "physical" },
  { title: "Great stamina", value: "great-stamina", category: "physical" },
  { title: "Physically strong", value: "physically-strong", category: "physical" },
  { title: "Very agile", value: "very-agile", category: "physical" },
  { title: "Good balance", value: "good-balance", category: "physical" },
  { title: "Strong in the air", value: "strong-in-air", category: "physical" },
  { title: "Hard to knock off the ball", value: "hard-to-knock-off", category: "physical" },
  { title: "Non-stop engine", value: "non-stop-engine", category: "physical" },
  { title: "High jumping reach", value: "jumping-reach", category: "physical" },

  { title: "Great tackler", value: "great-tackler", category: "defending" },
  { title: "Strong marker", value: "strong-marker", category: "defending" },
  { title: "Reads the game well", value: "reads-the-game", category: "defending" },
  { title: "Good interceptions", value: "good-interceptions", category: "defending" },
  { title: "Wins aerial duels", value: "wins-aerial-duels", category: "defending" },
  { title: "Great positional sense", value: "great-positional-sense", category: "defending" },
  { title: "Ball recovery specialist", value: "ball-recovery", category: "defending" },
  { title: "Excellent slide tackles", value: "excellent-slide-tackles", category: "defending" },
  { title: "Reliable last man", value: "reliable-last-man", category: "defending" },
  { title: "Strong 1v1 defender", value: "strong-1v1-defender", category: "defending" },

  { title: "Precise short passing", value: "precise-short-passing", category: "passing" },
  { title: "Great long balls", value: "great-long-balls", category: "passing" },
  { title: "Killer through balls", value: "killer-through-balls", category: "passing" },
  { title: "Excellent vision", value: "excellent-vision", category: "passing" },
  { title: "Dangerous crosses", value: "dangerous-crosses", category: "passing" },
  { title: "Set piece specialist", value: "set-piece-specialist", category: "passing" },
  { title: "Great corner delivery", value: "great-corner-delivery", category: "passing" },
  { title: "Free kick taker", value: "free-kick-taker", category: "passing" },
  { title: "Plays first-time passes", value: "first-time-passes", category: "passing" },
  { title: "Controls the tempo", value: "controls-tempo", category: "passing" },
  { title: "Switches play well", value: "switches-play", category: "passing" },
  { title: "Press resistant", value: "press-resistant", category: "passing" },
  { title: "Give-and-go expert (1-2s)", value: "give-and-go-expert", category: "passing" },
  { title: "Long throw-in threat", value: "long-throw-in", category: "passing" },

  { title: "Outside-foot passes", value: "outside-foot-pass", category: "passing" },
  { title: "Great dribbler", value: "great-dribbler", category: "dribbling" },
  { title: "Silky first touch", value: "silky-first-touch", category: "dribbling" },
  { title: "Close control under pressure", value: "close-control", category: "dribbling" },
  { title: "Beats players 1v1", value: "beats-players-1v1", category: "dribbling" },
  { title: "Skillful on the ball", value: "skillful-on-ball", category: "dribbling" },
  { title: "Carries the ball well", value: "carries-ball-well", category: "dribbling" },
  { title: "Creative flair", value: "creative-flair", category: "dribbling" },
  { title: "Reliable on the ball", value: "reliable-on-ball", category: "dribbling" },
  { title: "Great weak foot", value: "great-weak-foot", category: "dribbling" },
  { title: "Effective body feints", value: "body-feints", category: "dribbling" },
  { title: "Draws fouls easily", value: "draws-fouls", category: "dribbling" },
  { title: "Speed dribbler", value: "speed-dribbler", category: "dribbling" },

  { title: "Clinical finisher", value: "clinical-finisher", category: "shooting" },
  { title: "Powerful shot", value: "powerful-shot", category: "shooting" },
  { title: "Long range threat", value: "long-range-threat", category: "shooting" },
  { title: "Good with volleys", value: "good-volleys", category: "shooting" },
  { title: "Accurate headers", value: "accurate-headers", category: "shooting" },
  { title: "Cool in front of goal", value: "cool-in-front-of-goal", category: "shooting" },
  { title: "Finds the corners", value: "finds-the-corners", category: "shooting" },
  { title: "Penalty specialist", value: "penalty-specialist", category: "shooting" },
  { title: "Poacher instinct", value: "poacher-instinct", category: "shooting" },
  { title: "Scores from tight angles", value: "scores-tight-angles", category: "shooting" },
  { title: "Bending / Curled shots", value: "curled-shots", category: "shooting" },
  { title: "Times runs behind defense", value: "times-runs-behind", category: "shooting" },

  { title: "Great shot stopper", value: "great-shot-stopper", category: "goalkeeping" },
  { title: "Quick reflexes", value: "quick-reflexes", category: "goalkeeping" },
  { title: "Commands the area", value: "commands-area", category: "goalkeeping" },
  { title: "Good distribution", value: "good-distribution", category: "goalkeeping" },
  { title: "Brave in 1v1", value: "brave-1v1", category: "goalkeeping" },
  { title: "Good positioning (GK)", value: "good-gk-positioning", category: "goalkeeping" },
  { title: "Strong with high balls", value: "strong-high-balls", category: "goalkeeping" },
  { title: "Good with feet", value: "good-with-feet", category: "goalkeeping" },
  { title: "Sweeper keeper", value: "sweeper-keeper", category: "goalkeeping" },
  { title: "Penalty stopper", value: "penalty-stopper", category: "goalkeeping" },
  { title: "Quick double save reaction", value: "quick-second-recovery", category: "goalkeeping" },

  { title: "Natural leader", value: "natural-leader", category: "mental" },
  { title: "Great work rate", value: "great-work-rate", category: "mental" },
  { title: "Composure under pressure", value: "composure-under-pressure", category: "mental" },
  { title: "Smart decision maker", value: "smart-decision-maker", category: "mental" },
  { title: "Tactically intelligent", value: "tactically-intelligent", category: "mental" },
  { title: "Great communicator", value: "great-communicator", category: "mental" },
  { title: "Consistent performer", value: "consistent-performer", category: "mental" },
  { title: "Big game player", value: "big-game-player", category: "mental" },
  { title: "Never gives up", value: "never-gives-up", category: "mental" },
  { title: "Motivates teammates", value: "motivates-teammates", category: "mental" },
  { title: "Versatile (adapts to any role)", value: "versatile", category: "mental" },
  { title: "Tactically disciplined", value: "tactically-disciplined", category: "mental" },
  { title: "Unselfish team player", value: "unselfish-team-player", category: "mental" },
] as const;

export type Strength = (typeof strengths)[number]["value"];

export const countries = [
  { title: "Afghanistan", value: "af" },
  { title: "Åland Islands", value: "ax" },
  { title: "Albania", value: "al" },
  { title: "Algeria", value: "dz" },
  { title: "American Samoa", value: "as" },
  { title: "Andorra", value: "ad" },
  { title: "Angola", value: "ao" },
  { title: "Anguilla", value: "ai" },
  { title: "Antarctica", value: "aq" },
  { title: "Antigua and Barbuda", value: "ag" },
  { title: "Argentina", value: "ar" },
  { title: "Armenia", value: "am" },
  { title: "Aruba", value: "aw" },
  { title: "Australia", value: "au" },
  { title: "Austria", value: "at" },
  { title: "Azerbaijan", value: "az" },
  { title: "Bahamas", value: "bs" },
  { title: "Bahrain", value: "bh" },
  { title: "Bangladesh", value: "bd" },
  { title: "Barbados", value: "bb" },
  { title: "Belarus", value: "by" },
  { title: "Belgium", value: "be" },
  { title: "Belize", value: "bz" },
  { title: "Benin", value: "bj" },
  { title: "Bermuda", value: "bm" },
  { title: "Bhutan", value: "bt" },
  { title: "Bolivia", value: "bo" },
  { title: "Bonaire, Sint Eustatius and Saba", value: "bq" },
  { title: "Bosnia and Herzegovina", value: "ba" },
  { title: "Botswana", value: "bw" },
  { title: "Bouvet Island", value: "bv" },
  { title: "Brazil", value: "br" },
  { title: "British Indian Ocean Territory", value: "io" },
  { title: "British Virgin Islands", value: "vg" },
  { title: "Brunei", value: "bn" },
  { title: "Bulgaria", value: "bg" },
  { title: "Burkina Faso", value: "bf" },
  { title: "Burundi", value: "bi" },
  { title: "Cabo Verde", value: "cv" },
  { title: "Cambodia", value: "kh" },
  { title: "Cameroon", value: "cm" },
  { title: "Canada", value: "ca" },
  { title: "Cayman Islands", value: "ky" },
  { title: "Central African Republic", value: "cf" },
  { title: "Chad", value: "td" },
  { title: "Chile", value: "cl" },
  { title: "China", value: "cn" },
  { title: "Christmas Island", value: "cx" },
  { title: "Cocos (Keeling) Islands", value: "cc" },
  { title: "Colombia", value: "co" },
  { title: "Comoros", value: "km" },
  { title: "Cook Islands", value: "ck" },
  { title: "Costa Rica", value: "cr" },
  { title: "Côte d'Ivoire", value: "ci" },
  { title: "Croatia", value: "hr" },
  { title: "Cuba", value: "cu" },
  { title: "Curaçao", value: "cw" },
  { title: "Cyprus", value: "cy" },
  { title: "Czech Republic", value: "cz" },
  { title: "Democratic Republic of the Congo", value: "cd" },
  { title: "Denmark", value: "dk" },
  { title: "Djibouti", value: "dj" },
  { title: "Dominica", value: "dm" },
  { title: "Dominican Republic", value: "do" },
  { title: "Ecuador", value: "ec" },
  { title: "Egypt", value: "eg" },
  { title: "El Salvador", value: "sv" },
  { title: "England", value: "gb-eng" },
  { title: "Equatorial Guinea", value: "gq" },
  { title: "Eritrea", value: "er" },
  { title: "Estonia", value: "ee" },
  { title: "Eswatini", value: "sz" },
  { title: "Ethiopia", value: "et" },
  { title: "European Union", value: "eu" },
  { title: "Falkland Islands", value: "fk" },
  { title: "Faroe Islands", value: "fo" },
  { title: "Fiji", value: "fj" },
  { title: "Finland", value: "fi" },
  { title: "France", value: "fr" },
  { title: "French Guiana", value: "gf" },
  { title: "French Polynesia", value: "pf" },
  { title: "French Southern Territories", value: "tf" },
  { title: "Gabon", value: "ga" },
  { title: "Gambia", value: "gm" },
  { title: "Georgia", value: "ge" },
  { title: "Germany", value: "de" },
  { title: "Ghana", value: "gh" },
  { title: "Gibraltar", value: "gi" },
  { title: "Greece", value: "gr" },
  { title: "Greenland", value: "gl" },
  { title: "Grenada", value: "gd" },
  { title: "Guadeloupe", value: "gp" },
  { title: "Guam", value: "gu" },
  { title: "Guatemala", value: "gt" },
  { title: "Guernsey", value: "gg" },
  { title: "Guinea", value: "gn" },
  { title: "Guinea-Bissau", value: "gw" },
  { title: "Guyana", value: "gy" },
  { title: "Haiti", value: "ht" },
  { title: "Heard Island and McDonald Islands", value: "hm" },
  { title: "Honduras", value: "hn" },
  { title: "Hong Kong", value: "hk" },
  { title: "Hungary", value: "hu" },
  { title: "Iceland", value: "is" },
  { title: "India", value: "in" },
  { title: "Indonesia", value: "id" },
  { title: "Iran", value: "ir" },
  { title: "Iraq", value: "iq" },
  { title: "Ireland", value: "ie" },
  { title: "Isle of Man", value: "im" },
  { title: "Israel", value: "il" },
  { title: "Italy", value: "it" },
  { title: "Jamaica", value: "jm" },
  { title: "Japan", value: "jp" },
  { title: "Jersey", value: "je" },
  { title: "Jordan", value: "jo" },
  { title: "Kazakhstan", value: "kz" },
  { title: "Kenya", value: "ke" },
  { title: "Kiribati", value: "ki" },
  { title: "Kosovo", value: "xk" },
  { title: "Kuwait", value: "kw" },
  { title: "Kyrgyzstan", value: "kg" },
  { title: "Laos", value: "la" },
  { title: "Latvia", value: "lv" },
  { title: "Lebanon", value: "lb" },
  { title: "Lesotho", value: "ls" },
  { title: "Liberia", value: "lr" },
  { title: "Libya", value: "ly" },
  { title: "Liechtenstein", value: "li" },
  { title: "Lithuania", value: "lt" },
  { title: "Luxembourg", value: "lu" },
  { title: "Macau", value: "mo" },
  { title: "Madagascar", value: "mg" },
  { title: "Malawi", value: "mw" },
  { title: "Malaysia", value: "my" },
  { title: "Maldives", value: "mv" },
  { title: "Mali", value: "ml" },
  { title: "Malta", value: "mt" },
  { title: "Marshall Islands", value: "mh" },
  { title: "Martinique", value: "mq" },
  { title: "Mauritania", value: "mr" },
  { title: "Mauritius", value: "mu" },
  { title: "Mayotte", value: "yt" },
  { title: "Mexico", value: "mx" },
  { title: "Micronesia", value: "fm" },
  { title: "Moldova", value: "md" },
  { title: "Monaco", value: "mc" },
  { title: "Mongolia", value: "mn" },
  { title: "Montenegro", value: "me" },
  { title: "Montserrat", value: "ms" },
  { title: "Morocco", value: "ma" },
  { title: "Mozambique", value: "mz" },
  { title: "Myanmar", value: "mm" },
  { title: "Namibia", value: "na" },
  { title: "Nauru", value: "nr" },
  { title: "Nepal", value: "np" },
  { title: "Netherlands", value: "nl" },
  { title: "New Caledonia", value: "nc" },
  { title: "New Zealand", value: "nz" },
  { title: "Nicaragua", value: "ni" },
  { title: "Niger", value: "ne" },
  { title: "Nigeria", value: "ng" },
  { title: "Niue", value: "nu" },
  { title: "Norfolk Island", value: "nf" },
  { title: "North Korea", value: "kp" },
  { title: "North Macedonia", value: "mk" },
  { title: "Northern Ireland", value: "gb-nir" },
  { title: "Northern Mariana Islands", value: "mp" },
  { title: "Norway", value: "no" },
  { title: "Oman", value: "om" },
  { title: "Pakistan", value: "pk" },
  { title: "Palau", value: "pw" },
  { title: "Palestine", value: "ps" },
  { title: "Panama", value: "pa" },
  { title: "Papua New Guinea", value: "pg" },
  { title: "Paraguay", value: "py" },
  { title: "Peru", value: "pe" },
  { title: "Philippines", value: "ph" },
  { title: "Pitcairn Islands", value: "pn" },
  { title: "Poland", value: "pl" },
  { title: "Portugal", value: "pt" },
  { title: "Puerto Rico", value: "pr" },
  { title: "Qatar", value: "qa" },
  { title: "Republic of the Congo", value: "cg" },
  { title: "Réunion", value: "re" },
  { title: "Romania", value: "ro" },
  { title: "Russia", value: "ru" },
  { title: "Rwanda", value: "rw" },
  { title: "Saint Barthélemy", value: "bl" },
  { title: "Saint Helena, Ascension and Tristan da Cunha", value: "sh" },
  { title: "Saint Kitts and Nevis", value: "kn" },
  { title: "Saint Lucia", value: "lc" },
  { title: "Saint Martin", value: "mf" },
  { title: "Saint Pierre and Miquelon", value: "pm" },
  { title: "Saint Vincent and the Grenadines", value: "vc" },
  { title: "Samoa", value: "ws" },
  { title: "San Marino", value: "sm" },
  { title: "São Tomé and Príncipe", value: "st" },
  { title: "Saudi Arabia", value: "sa" },
  { title: "Scotland", value: "gb-sct" },
  { title: "Senegal", value: "sn" },
  { title: "Serbia", value: "rs" },
  { title: "Seychelles", value: "sc" },
  { title: "Sierra Leone", value: "sl" },
  { title: "Singapore", value: "sg" },
  { title: "Sint Maarten", value: "sx" },
  { title: "Slovakia", value: "sk" },
  { title: "Slovenia", value: "si" },
  { title: "Solomon Islands", value: "sb" },
  { title: "Somalia", value: "so" },
  { title: "South Africa", value: "za" },
  { title: "South Georgia", value: "gs" },
  { title: "South Korea", value: "kr" },
  { title: "South Sudan", value: "ss" },
  { title: "Spain", value: "es" },
  { title: "Sri Lanka", value: "lk" },
  { title: "Sudan", value: "sd" },
  { title: "Suriname", value: "sr" },
  { title: "Svalbard and Jan Mayen", value: "sj" },
  { title: "Sweden", value: "se" },
  { title: "Switzerland", value: "ch" },
  { title: "Syria", value: "sy" },
  { title: "Taiwan", value: "tw" },
  { title: "Tajikistan", value: "tj" },
  { title: "Tanzania", value: "tz" },
  { title: "Thailand", value: "th" },
  { title: "Timor-Leste", value: "tl" },
  { title: "Togo", value: "tg" },
  { title: "Tokelau", value: "tk" },
  { title: "Tonga", value: "to" },
  { title: "Trinidad and Tobago", value: "tt" },
  { title: "Tunisia", value: "tn" },
  { title: "Turkey", value: "tr" },
  { title: "Turkmenistan", value: "tm" },
  { title: "Turks and Caicos Islands", value: "tc" },
  { title: "Tuvalu", value: "tv" },
  { title: "Uganda", value: "ug" },
  { title: "Ukraine", value: "ua" },
  { title: "United Arab Emirates", value: "ae" },
  { title: "United Kingdom", value: "gb" },
  { title: "United Nations", value: "un" },
  { title: "United States", value: "us" },
  { title: "United States Minor Outlying Islands", value: "um" },
  { title: "United States Virgin Islands", value: "vi" },
  { title: "Uruguay", value: "uy" },
  { title: "Uzbekistan", value: "uz" },
  { title: "Vanuatu", value: "vu" },
  { title: "Vatican City", value: "va" },
  { title: "Venezuela", value: "ve" },
  { title: "Vietnam", value: "vn" },
  { title: "Wales", value: "gb-wls" },
  { title: "Wallis and Futuna", value: "wf" },
  { title: "Western Sahara", value: "eh" },
  { title: "Yemen", value: "ye" },
  { title: "Zambia", value: "zm" },
  { title: "Zimbabwe", value: "zw" },
] as const;

export type CountryCode = (typeof countries)[number]["value"];

/**
 * Get the flagcdn URL for a given country code
 * @param code ISO 3166-1 alpha-2 code (lowercase)
 * @param width Width in pixels (default 40)
 */
export function getFlagUrl(code: string, width: number = 40): string {
  return `https://flagcdn.com/w${width}/${code}.png`;
}
